# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
safe: true


# edit here to achieve your personal greatness
url: http://elisescu.com/
baseurl: ""
title: Bits and pieces
author: Elis Popescu
description: Personal blog and resume
avatar: profile.png
#email: yourname@email.com
github: elisescu
twitter: elisescu
linkedin: elisescu
#Comment out if you don't want disqus
google_analytics: "UA-71598504-4"


# Resume related data
name: Elis Popescu
website: elisescu.com
postcode: 2400
city: Copenhagen
country: Denmark

# needed for travis-ci build
exclude: [vendor]
