title: Elis Popescu
description: Elis Popescu's blog

url: http://blog.elisescu.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: elisescu
   twitter: elisescu

google_analytics: "UA-71598504-4"
