name: Basic Code Quality checks

on:
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  basic-code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
      - name: Checking for whitespace errors
        run: |
          git fetch origin master
          git diff origin/master --check
      - name: Checking for code formatting issues
        run: |
          pip install black && black --check app tekudo
          cd frontend && npm install prettier && npm run prettiercheck
      - name: Checking for Typescript errors
        run: |
          cd frontend && node --version
          npm ci && npm run tscheck

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['16.13.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Buildin the code
        run: |
          cd frontend && npm ci && npm run build

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.9'
          architecture: 'x64'
      - run: |
          pip install -r requirements.txt && \
          DATABASE_URL='sqlite:////tmp/test-django.sqlite' ./manage.py test --failfast